### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by jayvdb** [berkeleydb/libdb#1]
Many new releases to include from http://www.oracle.com/technetwork/database/database-technologies/berkeleydb/downloads/index-082944.html

**Comment by nanonyme** [comment]
BerkeyleyDB changed license from BSD to AGPL in 6.x making it essentially a different library.

**Comment by DrewRay** [comment]
see https://github.com/Positeral/libdb5

**Comment by GitMensch** [comment]
It would be nice to possibly have this repo integrate the last update under sleepycat ([5.3.28](download.oracle.com/berkeley-db/db-5.3.28.tar.gz)) to this repo, too.

Just in case someone comes here in search of the historic versions: https://bazaar.launchpad.net/~bdb/berkeley-db/trunk/changes/5?start_revid=45 is quite complete (1.8.5, 1.8.6, 2.7.7, 3.0.x, 3.1.x,  3.2.x, 3.3.x, 4.0.x, ... 4.8.x).

I still have to find a repo which has all releases from 1.8.5-5.3.28, ideally unpatched, possibly with a branch for each containing patches should they exist...

**Comment by baiwfg2** [comment]
It is very pitiful that we cannot see the commit history and issues of BDB, which is very important to understand the implementation.

**Comment by gburd** [comment]
Lewis,

It is unfortunate that the history of Berkeley DB development isn't
published and will never make it into the public eye.  When I joined
Sleepcat in 2002 we used an in-house bug system (based on sed, awk, etc.)
and we used that until we were integrated into Oracle post-acquisition.
Those issues, conversations and other information is private and owned by
Oracle.  It's also riddled with information that is internal, secure, or
otherwise hard to publish.  So, while I'd not say "pitiful" I would say
that today's development in the open is a privilege and very helpful to
others in the opensource world as a source of information when learning
about a software system.

I've not worked for Oracle for years and years now but I'd imagine that the
full history of Berkeley DB is unlikely to ever be published.

-greg
